#!/usr/bin/python3
def raise_exception():
    a = list()
    b = 2
    print("{}".format(a + b))
